### ISSUE TITLE
Error: Command failed: git -c core.longpaths=true config --get remote.origin.url

### ISSUE THREAD

**Issue by peterblazejewicz** [PolymerElements/test-fixture#30]
Hi,
I'm not perfectly sure the problem is related to this package, but  've receive an error when PSK project is scaffolded with `yo polymer` on Windows. So far I'm not able to quickly locate possible source of that problem:
```
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:827:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:475:12)
npm WARN addRemoteGit  polymerelements/test-fixture resetting remote C:\Users\{USER}\AppData\Roaming\npm-cache\_git-remotes\git-github-com-polymerelements-test-fixture-git-4485c51b because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
```

## Expected outcome

No errors produced

## Steps to reproduce

Run `yo polymer`, including all optional settings (WTC, Recipes).

Windows 10
NPM 3.5.2
Node: 4.4.0
Yo: 1.7.0
Git: 2.7.1 Windows (GitHub Desktop client)
generator-polymer:  1.2.10

**Comment by Everlag** [comment]
I encountered this issue when installing polymer-cli using cygwin. Installing it with command prompt solved the issue.

I have git 2.8.3 in cygwin and git 1.9.5 in command prompt. I'd lean towards git being the issue in this case.

**Comment by jodekirk** [comment]
I received this error when trying to install polymer-cli using npm behind a corporate firewall blocking ports 22 and 443.
npm -g install polymer-cli

After trying 50 things I got around the error by installing polymer-test-fixture first:
npm i -g @polymer/test-fixture
